### ISSUE TITLE
How to connect to Postgres inside docker container

### ISSUE THREAD

**Issue by ArthurZaharov** [fs/rails-base-graphql-api#137]
Usually, we run `bin/rails db` for this.

**Comment by EvgeniyEsaulkov** [comment]
@ArthurZaharov have you tried the next?
```bash
docker-compose exec app bin/rails db
```
Password for user postgres: "password"

**Comment by AleksandrSeleznev** [comment]
@EvgeniyEsaulkov it works! Thanks a lot!

**Comment by ArthurZaharov** [comment]
@EvgeniyEsaulkov I think that we should have this information (along with other common commands) somewhere in README or in wiki.

**Comment by EvgeniyEsaulkov** [comment]
@ArthurZaharov sure, I will add it with small PR this week
