### ISSUE TITLE
Validate allowed file extensions in PresignData endpoint

### ISSUE THREAD

**Issue by ArthurZaharov** [fs/rails-base-graphql-api#138]
@AleksandrSeleznev raised the concern that we cannot validate files allowed for different models in PresignData endpoint. For example, to user avatar we should validate that user can upload only images, for Document model we need to validate that allowed only text documents. At the moment we cannot do that since we have common validation of file extension in the PresignData.

**Comment by EvgeniyEsaulkov** [comment]
@mikhail-kilin and I created PR #163 that adds type and extension validations to uploader. This way we can to not validate file type in `PresignData` mutation or allow types used in our application. In case user will try to upload file with invalid type he will receive an error with `SignUp` or `UpdateUser` mutation. Something like this: "avatar: 'type must be one of: image/jpeg, image/png, image/webp'"

@AleksandrSeleznev  @ArthurZaharov what do you think?
