### ISSUE TITLE
Validate headers during uploading presigned file to the local storage

### ISSUE THREAD

**Issue by AleksandrSeleznev** [fs/rails-base-graphql-api#144]
Uploading presigned file locally via `POST` to `http://localhost:3000/images/upload` does not validate input headers in the request.
For example, we could leave `Content-Type` and `Content-Disposition` headers empty here:
![image](https://user-images.githubusercontent.com/79082097/113451208-cc654880-9401-11eb-867a-1b5ee85362cd.png)

Is it necessary to validate these headers somehow?
Or is it necessary to keep these headers as mandatory in order to upload presigned file?
If I'm not mistaken, the `LocalStorage` custom class inherits from `Shrine::Storage::FileSystem` class. It calls the `upload` method finally and it doesn't use this information.

```ruby
# File 'lib/shrine/storage/file_system.rb', line 50

def upload(io, id, move: false, **)
  if move && movable?(io)
    move(io, path!(id))
  else
    IO.copy_stream(io, path!(id))
  end

  path(id).chmod(permissions) if permissions
end
```

source: https://www.rubydoc.info/gems/shrine/3.3.0/Shrine/Storage/FileSystem#upload-instance_method

**Comment by EvgeniyEsaulkov** [comment]
We implemented `LocalStorage` to use it in development environment when developer hasn't (or doesn't want) to specify AWS S3 credentials. That's why I think we have to realize similar behaviour as S3 storage. AWS S3 doesn't require these fields:
![image](https://user-images.githubusercontent.com/58729845/113500648-61626180-9528-11eb-887c-0aafb7a18313.png)

**Comment by AleksandrSeleznev** [comment]
> We implemented `LocalStorage` to use it in development environment when developer hasn't (or doesn't want) to specify AWS S3 credentials. That's why I think we have to realize similar behaviour as S3 storage. AWS S3 doesn't require these fields:
> ![image](https://user-images.githubusercontent.com/58729845/113500648-61626180-9528-11eb-887c-0aafb7a18313.png)

Got this! Thank you for the explanation.
