### ISSUE TITLE
Unexpected Internal Error during signout for the second time

### ISSUE THREAD

**Issue by AleksandrSeleznev** [fs/rails-base-graphql-api#166]
It throws an error when AccessToken is valid, but all of the RefreshTokens have been destroyed.
```ruby
module AuthenticableUser
  private

  def current_user
    return unless token && payload
    return execution_error(error_data: authentication_error) unless active_refresh_token?

    User.find_by(id: payload["sub"])
  end
```
Here `current_user` will return `GraphQL::ExecutionError`.
Hence, here will return `true`:
```ruby
module AuthenticableGraphqlUser
  extend ActiveSupport::Concern

  private

  def ready?(*)
    return true if current_user

    raise execution_error(error_data: authentication_error)
  end
```

![image](https://user-images.githubusercontent.com/79082097/125271989-9e9a7480-e30b-11eb-9a05-6a984bb52add.png)

**Comment by DmitryBarskov** [comment]
@AleksandrSeleznev please describe steps to reproduce this bug.

**Comment by EvgeniyEsaulkov** [comment]
We can implement some sort of blacklist where we will store access tokens after user signed out. Also we need to add background task that will remove expired access tokens from this list.

**Comment by AleksandrSeleznev** [comment]
What is the point of implementing the Blacklisted/Whitelisted tables for storing access token expirations?
At this moment we're using refresh tokens in order to validate access tokens.
We have the 2 steps of validating the tokens:

1. Access token expiration time (1 hour);
2. Refresh tokens with the appropriate `jti`.

I think, we have a bug right here:
```ruby
module AuthenticableUser
  private

  def current_user
    return unless token && payload
    return execution_error(error_data: authentication_error) unless active_refresh_token?

    User.find_by(id: payload["sub"])
  end
```
We shouldn't return `execution_error` when the system didn't find out active refresh tokens. It would be better to return only `nil`.

In medagregator project we implemented the following approach:
```ruby
module AuthenticableUser
  private

  def current_user
    return unless token && payload
    return unless active_refresh_token?

    User.find_by(id: payload["sub"])
  end
```

Also, I assume that it would be better to use Redis in order to store refresh tokens instead of Postgres? What do you think about this?

**Comment by EvgeniyEsaulkov** [comment]
@AleksandrSeleznev the point is that access token should become invalid after user signs out. Then `current_user` will return `nil` in the case described in this issue
