### ISSUE TITLE
User should be able to save a link to avatar image

### ISSUE THREAD

**Issue by ArthurZaharov** [fs/rails-base-graphql-api#42]
1. The image uploading to AWS should be implemented on FE/mobile sides.
2. They should send the link to uploaded image to API

**Comment by EvgeniyEsaulkov** [comment]
I think we should implement the next scheme:

![direct-uploads-diagram](https://user-images.githubusercontent.com/58729845/84245794-442e5380-ab0e-11ea-932b-f39cbbef594f.png)

There is a couple of good articles from Evil Martians that describe whole process:
- Front-end sends metadata for uploaded file;
- Server responds with the object that includes URL for upload and signed blob id:
```
{
      direct_upload: {
        url: blob.service_url_for_direct_upload,
        # NOTE: we pass headers as JSON since they have no schema
        headers: blob.service_headers_for_direct_upload.to_json,
        blob_id: blob.id,
        signed_blob_id: blob.signed_id
      }
    }
```
- Front-end uploads the file to AWS S3 and sends `signed_blob_id` to server to store it in the database

The article describing this process - https://evilmartians.com/chronicles/active-storage-meets-graphql-direct-uploads

Also there is part 2 describing how to deal with variants (thumb, small, medium) for uploaded images - https://evilmartians.com/chronicles/active-storage-meets-graphql-pt-2-exposing-attachment-urls. We can use these articles as a base for this task.

**Comment by EvgeniyEsaulkov** [comment]
React native example from the article above - https://gist.github.com/Saionaro/7ee0e2c02749e2729dc429c9e9bfa7f3

There are no checksum in file metadata, just filename, size and content type.

**Comment by EvgeniyEsaulkov** [comment]
As for Shrine they have similar flow - https://shrinerb.com/docs/direct-s3, but use the separate endpoint to get URL, params, and headers needed for a single upload directly to the storage service. Also it requires additional plugin -https://shrinerb.com/docs/plugins/presign_endpoint

So I guess using Active Storage for this task is more pretty and clear
