### ISSUE TITLE
Guest user should be able to see the activity feed

### ISSUE THREAD

**Issue by ArthurZaharov** [fs/rails-base-graphql-api#46]

**Comment by EvgeniyEsaulkov** [comment]
I suggest to create the model `PublicActivity` with the next fields:
```ruby
create_table :public_activities do |t|
  t.string :title, null: false
  t.text :body, null: true
  t.references :user, foreign_key: true, null: false

  t.timestamps
end
```
PublicActivity belongs to User, User has many Public Activities. After user has created wi will register activity for this action:
```ruby
user.public_activities.create(title: "User registered", body: "New user registered with the next attributes: First name - #{user.first_name}, Last name - #{user.last_name}"
```

Maybe we should add also `activity_type` field ('registration' for example above). We can use `enum` to store this field.

**Comment by ArthurZaharov** [comment]
@EvgeniyEsaulkov Should we use the `Activity` model? I think that we should not specify the `public` word here since the `Activity` will be useful in real projects.
As for `activity_type` let's add additional fields later. For now, it will be enough if we have a title and body fields.
