### ISSUE TITLE
User should be able to fetch paginated activities list

### ISSUE THREAD

**Issue by ArthurZaharov** [fs/rails-base-graphql-api#79]
### Why
We will have many activities records. Therefore we should return them by small pages.
[GraphQL docs.](https://graphql.org/learn/pagination/)
[Related Article](https://www.apollographql.com/blog/understanding-pagination-rest-graphql-and-relay-b10f835549e7)

**As User**
**I want** to be able to get paginated activity data

### Acceptance Criteria

```gherkin
Scenario: 
Given a User
When he makes activities GraphQL request with `first` and `offset` arguments
Then should receive only a piece of his activities
```
```ruby
me {
  id
  email
  activities(first: 2, offset: 2) {
    id
    title
    body
    event
    createdAt
  }
}
```

**Notes:**
We can choose different argument names. For example, it could be page=2 and count=30.

**Comment by EvgeniyEsaulkov** [comment]
@ArthurZaharov I guess this issue can be closed as we realized cursor-based pagination (#83)
