### ISSUE TITLE
Investigate the ability to implement cursor based pagination

### ISSUE THREAD

**Issue by ArthurZaharov** [fs/rails-base-graphql-api#83]
### Why
Cursor-based pagination is the most powerful.
[GraphQL docs.](https://graphql.org/learn/pagination/)
[Related Article from GraphQL docs](https://www.apollographql.com/blog/understanding-pagination-rest-graphql-and-relay-b10f835549e7)

**Notes:**
The problem with cursor-based pagination is that we should have ordered cursor for each sorted relation type. Suppose, if we will use ID as a cursor.
If we order relation by id (ascending or descending) it will work. We can select 2 elements after ID=2 using SQL like `where("id > 2").limit(2)`
```ruby
ID=1
ID=2
ID=3
ID=4
```

But if the order of IDs changes for example when the relation was sorted then we cannot use SQL to get the correct result
```ruby
ID=2
ID=4
ID=1
ID=3
```

**Comment by EvgeniyEsaulkov** [comment]
I guess we can use [Cursor Connections Specification](https://relay.dev/graphql/connections.htm) to reach our goal. It returns each record as a node with unique cursor field (it's not identical to record id!). It looks like this:
```graphql
user {
  email      
  activities {
    edges {
      node {
        title
        createdAt
      }
      cursor
    }
  }
}
```
Result:
```json
"user": {
  "email": "darth.vader@example.com",
  "activities": {
    "edges": [
      {
        "node": {
          "title": "User updated",
          "createdAt": "2020-07-02T09:13:44Z"
        },
        "cursor": "MQ"
      },
      {
        "node": {
          "title": "User registered",
          "createdAt": "2020-07-02T08:11:44Z"
        },
        "cursor": "Mg"
      },
      {
        "node": {
          "title": "User logged in",
          "createdAt": "2020-07-02T09:12:29Z"
        },
        "cursor": "Mw"
      },
      {
        "node": {
          "title": "User logged in",
          "createdAt": "2020-07-02T09:12:51Z"
        },
        "cursor": "NA"
      }
    ]
  }
}
```
Using cursors we can execute query like this:
```graphql
user {
  email
  activities(first:2, after: "MQ") {
    edges {
      node {
        title
        createdAt
      }
      cursor
    }
  }
}
```
It will return the next result:
```json
"user": {
  "email": "darth.vader@example.com",
  "activities": {
    "edges": [
      {
        "node": {
          "title": "User registered",
          "createdAt": "2020-07-02T08:11:44Z"
        },
        "cursor": "Mg"
      },
      {
        "node": {
          "title": "User logged in",
          "createdAt": "2020-07-02T09:12:29Z"
        },
        "cursor": "Mw"
      }
    ]
  }
}
```
Also we can return page info like this:
```graphql
activities(first:2, after: "MQ") {
  edges {
    node {
      title
      createdAt
    }
    cursor
  }
  pageInfo {
    startCursor
    endCursor
    hasPreviousPage
    hasNextPage
  }
}
```
