### ISSUE TITLE
Investigate advantages of one input field in the mutation

### ISSUE THREAD

**Issue by ArthurZaharov** [fs/rails-base-graphql-api#93]
Related articles - https://atheros.ai/blog/graphql-best-practices-for-graphql-schema-design

**Comment by EvgeniyEsaulkov** [comment]
The single advantage I found is more simple request from the client side. Now we need to form something like this:
```graphql
mutation SignUp($email: String!, $password: String!, $firstName: String, $lastName: String) {
  signup(email: $email, password: $password, firstName: $firstName, lastName: $lastName) {
    me {
      id
      email
    }
    accessToken
    refreshToken
  }
}
```

With `InputObject` the same request will look like this:
```graphql
mutation SignUp($input: SignupInput!) {
  signup(input: $input) {
    me {
      id
      email
    }
    accessToken
    refreshToken
  }
}
``` 
with query variables:
```graphql
{
  "input": {
	"email": "john.tolkien@example.com",
  	"password": "654321",
  	"firstName": "John",
  	"lastName": "Tolkien"
  }
}
```

**Comment by Nikita-Polyakov** [comment]
We are ready to use `input objects`, if you change both `queries` and `mutations` inputs (not only mutations)

**Comment by ArthurZaharov** [comment]
@Nikita-Polyakov It does not make sence to use input in `queries` as for me. How it should work from your opinion?
