### ISSUE TITLE
Investigate ActionPolicy gem and how we can use it

### ISSUE THREAD

**Issue by ArthurZaharov** [fs/rails-base-graphql-api#99]
Related articles
[Github repo](https://github.com/palkan/action_policy)
[Exposing permissions in GraphQL APIs with Action Policy](https://evilmartians.com/chronicles/exposing-permissions-in-graphql-apis-with-action-policy)

**Comment by DmitryBarskov** [comment]
The **action_policy-graphql** is an integration of **action-policy** (which is preferred authorization library in our company) with **GraphQL** Ruby Gem (this template is built on top of it).

Its features:

- Authorization for individual fields and mutations
- Scoping
- Showing permissions to API consumers

**Comment by DmitryBarskov** [comment]
To use it first start with ActionPolicy Gem and create a PolicyObject for some model.

To enable exposing policies inlucde `ActionPolicy::GraphQL::Behaviour` in GraphQL base classes
```ruby
class Types::BaseObject < GraphQL::Schema::Object
  include ActionPolicy::GraphQL::Behaviour
end

# For using authorization helpers in mutations
class Types::BaseMutation < GraphQL::Schema::Mutation
  include ActionPolicy::GraphQL::Behaviour
end

# For using authorization helpers in resolvers
class Types::BaseResolver < GraphQL::Schema::Resolver
  include ActionPolicy::GraphQL::Behaviour
end
```

Then e.g. we have
```ruby
class Types::QueryType < Types::BaseObject
  field :activities, resolver: Resolvers::Activities
end
```
We should add `authorize: true`
```ruby
class Types::QueryType < Types::BaseObject
  field :activities, resolver: Resolvers::Activities, authorize: true
end
```

Then we can add field authorization for a field
```ruby
class UserType < Types::BaseObject
  field :id, ID, null: false
  # ...
  field :activities, [ActivityType], null: true, authorized_scope: { with: ActivityPolicy }
  # OR
  field :activities, [ActivityType], null: true, authorized_scope: true
end
```

Expose rules:
```ruby
class UserType < Types::BaseObject
  # ...
  field :activities, [ActivityType], null: true, authorized_scope: true
  expose_authorization_rules :edit?, :destroy?
end
```

---

I think we can apply this to make some user activities private.
